### ISSUE TITLE
Error when creating an instance of flask_fontawesome

### ISSUE THREAD

**Issue by kenlittleton** [heartsucker/flask-fontawesome#6]
Creating an instance of flask_fontawesome without passing 'app' returns a NoneType error in version 0.1.3. Doesn't happen in 0.1.1.

```python
>>> from flask_fontawesome import FontAwesome
>>> fa = FontAwesome()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ken/Dev/cranialsoft/shit/.venv/lib/python3.8/site-packages/flask_fontawesome/__init__.py", line 192, in __init__
    app.extensions = {}
AttributeError: 'NoneType' object has no attribute 'extensions'
```

**Comment by kenlittleton** [comment]
Sorry @heartsucker, I can't do a pull req right now. But proposed fix is edit :__init__.py: and indent lines 191-193 so they're in the "if app is not None:" block.

**Comment by heartsucker** [comment]
I pushed a fix and will push a new version to PyPI shortly. Thanks for reporting this.
